### ISSUE TITLE
spell check topics

### ISSUE THREAD

**Issue by marakew** [8sileus/zedio#17]
asychronous -> asyNchronous

**Comment by 8sileus** [comment]
> asychronous -> asyNchronous

done

**Comment by 8sileus** [comment]
> no
> i mean keywords of topics

sorry 
done

**Comment by marakew** [comment]
great
this is the reason why I found your project now

In general, I’ve been waiting for a long time for someone to start porting Tokyo to C++ and was thinking about starting this
