### ISSUE TITLE
idle mistake, fetch_add instead load

### ISSUE THREAD

**Issue by marakew** [8sileus/zedio#19]
https://github.com/8sileus/zedio/blob/35d9577103aca53c45ce81e0ed9ce352d1993b05/zedio/runtime/multi_thread/idle.hpp#L31

https://github.com/tokio-rs/tokio/blob/6fcd9c02176bf3cd570bc7de88edaa3b95ea480a/tokio/src/runtime/scheduler/multi_thread/idle.rs#L154

https://github.com/tokio-rs/tokio/commit/7c8b8877d440629ab9a27a2c9dcef859835d3536

yes may be its more tokio related issues
but anyway

**Comment by 8sileus** [comment]
Yes
Thanks for your reminding, mistakes have been corrected.
```
A load operation with this memory order performs an acquire operation, a store performs a release operation, and read-modify-write performs both an acquire operation and a release operation, plus a single total order exists in which all threads observe all modifications in the same order
```
